#!/bin/bash
#SBATCH --uenv=eurohack/24.9:v2
#SBATCH --view=modules
#SBATCH --ntasks-per-node=2
##SBATCH --ntasks=
#SBATCH --nodes=2
#SBATCH --output=out-%j.out
#SBATCH -C gpu
##SBATCH --partition=debug
#SBATCH --time=00:05:00
#SBATCH --reservation=eurohack24
export NSYS_NVTX_PROFILER_REGISTER_ONLY=0
export CUDA_LAUNCH_BLOCKING=1
#
srun nsys profile -t cuda,nvtx,mpi -o driftTest-2-nsys.%p $HOME/git/opalx/build/src/opalx DriftTest-2/DriftTest-2.in --info 5 --kokkos-map-device-id-by=mpi_rank
