#!/bin/bash

KEYWORDS="Timings|Date|"

# Check if number of ranks is provided as an argument
if [ -z "$1" ]; then
    NUM_RANKS=1
else
    # Assign the number of ranks to a variable
    NUM_RANKS=$1
fi

# Loop over all .in files in the current directory
for input_file in *.in; do

  # Extract the basename (filename without the extension)
  base_name=$(basename "$input_file" .in)

  # Define the output file
  output_file="${base_name}.p${NUM_RANKS}.out"
  
  echo "Processing $input_file with $NUM_RANKS ranks..."
  mpirun -np ${NUM_RANKS} opalx "$input_file" --info 5 >  "$output_file" 2>&1


  diff <(grep -v -f reference-solution/veto.txt $output_file) <(grep -v -f reference-solution/veto.txt reference-solution/$output_file)

  if [ $? -eq 0 ]; then
      echo "The files $output_file match after ignoring the specified keywords in reference-solution/veto.txt."
  else
      echo "The files differ."
fi

done
